# Generated by Django 2.2.5 on 2019-10-09 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windfarm', models.CharField(blank=True, max_length=120)),
                ('wtg_model', models.CharField(max_length=120)),
                ('wtg_number', models.CharField(max_length=120)),
                ('kwh', models.CharField(blank=True, max_length=10)),
                ('turbine_work_hours', models.CharField(blank=True, max_length=10)),
                ('hub_heigth', models.CharField(blank=True, max_length=10)),
                ('customer', models.CharField(blank=True, max_length=120)),
                ('blade_type', models.CharField(max_length=120)),
                ('set_number', models.CharField(blank=True, max_length=120)),
                ('blade_A_number', models.CharField(blank=True, max_length=120)),
                ('blade_B_number', models.CharField(blank=True, max_length=120)),
                ('blade_C_number', models.CharField(blank=True, max_length=120)),
                ('inspection_period', models.DateField(auto_now_add=True)),
                ('service_company', models.CharField(blank=True, max_length=120)),
                ('name_of_technicians', models.CharField(max_length=120)),
                ('temperature', models.CharField(blank=True, max_length=10)),
                ('humidity', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blade', models.CharField(max_length=20)),
                ('blade_number', models.CharField(max_length=20, null=True)),
                ('finding', models.CharField(max_length=20)),
                ('inspection_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ps_ss_le_te', models.CharField(choices=[('PS', 'PS - Preasure Side'), ('SS', 'SS - Section Side'), ('LE', 'LE - Leading Edge'), ('TE', 'TE - Trailing Edge')], default='LE', max_length=2)),
                ('pd_from', models.CharField(max_length=10, null=True)),
                ('damage_type', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], default='one', max_length=1)),
                ('length', models.CharField(max_length=10)),
                ('width', models.CharField(blank=True, max_length=10)),
                ('inspection_type', models.CharField(choices=[('INT', 'internal'), ('EXT', 'external')], default='INT', max_length=3)),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blades', to='bladework.Turbine')),
            ],
        ),
    ]
