# Generated by Django 2.2.5 on 2019-10-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('blade_number', models.CharField(blank=True, max_length=12)),
                ('inspection_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtg_number', models.CharField(max_length=120)),
                ('windfarm', models.CharField(blank=True, max_length=120)),
                ('wtg_manufacturer', models.CharField(blank=True, max_length=120)),
                ('wtg_model', models.CharField(max_length=120)),
                ('customer', models.CharField(blank=True, max_length=120)),
                ('hub_heigth', models.CharField(blank=True, max_length=10)),
                ('blade_type', models.CharField(blank=True, max_length=10)),
                ('blade_length', models.CharField(blank=True, max_length=10)),
                ('set_number', models.CharField(blank=True, max_length=12)),
                ('kwh', models.CharField(blank=True, max_length=10)),
                ('turbine_work_hours', models.CharField(blank=True, max_length=10)),
                ('inspection_period', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PS', 'PS - Preasure Side'), ('SS', 'SS - Section Side'), ('LE', 'LE - Leading Edge'), ('TE', 'TE - Trailing Edge')], default='LE', max_length=2)),
                ('distance_from', models.CharField(max_length=10, null=True)),
                ('damage_type', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
                ('length', models.CharField(max_length=10)),
                ('width', models.CharField(blank=True, max_length=10)),
                ('blade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bladework.Blade')),
            ],
        ),
        migrations.AddField(
            model_name='blade',
            name='turbine',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='bladework.Turbine'),
        ),
    ]
