# Generated by Django 2.2.5 on 2019-10-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windfarm', models.CharField(max_length=120)),
                ('wtg_model', models.CharField(max_length=120)),
                ('wtg_number', models.CharField(max_length=120)),
                ('kwh', models.CharField(max_length=20)),
                ('turbine_work_hours', models.CharField(max_length=20)),
                ('hub_heigth', models.CharField(max_length=120)),
                ('customer', models.CharField(max_length=120)),
                ('blade_type', models.CharField(max_length=120)),
                ('set_number', models.CharField(max_length=120)),
                ('blade_a_number', models.CharField(max_length=120)),
                ('blade_b_number', models.CharField(max_length=120)),
                ('blade_c_number', models.CharField(max_length=120)),
                ('inspection_period', models.CharField(max_length=120)),
                ('service_company', models.CharField(max_length=120)),
                ('name_of_technicians', models.CharField(max_length=120)),
                ('temperature', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blade', models.CharField(max_length=20)),
                ('finding', models.CharField(max_length=20)),
                ('ps_ss_le_te', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=60)),
                ('damage_type', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('length', models.CharField(max_length=60)),
                ('width', models.TextField(blank=True, max_length=1000)),
                ('inspection_type', models.CharField(max_length=20)),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blades', to='bladework.Turbine')),
            ],
        ),
    ]
