# Generated by Django 2.2.5 on 2019-10-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bladework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='damage',
            name='inspection_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='inspection_period',
            field=models.CharField(max_length=20),
        ),
    ]
