# Generated by Django 2.2.5 on 2019-10-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bladework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='email',
        ),
    ]
