# Generated by Django 2.2.5 on 2019-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bladework', '0002_auto_20191009_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='category',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four')], default='one', max_length=1),
        ),
        migrations.AlterField(
            model_name='damage',
            name='inspection_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='inspection_period',
            field=models.DateField(auto_now_add=True),
        ),
    ]
