# Generated by Django 2.2.5 on 2019-10-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bladework', '0003_auto_20191009_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='blade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='damage',
            name='category',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
    ]
