# Generated by Django 2.2.5 on 2019-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bladework', '0003_auto_20191009_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='inspection_type',
            field=models.CharField(choices=[('INT', 'internal'), ('EXT', 'external')], default='INT', max_length=3),
        ),
    ]
