# Generated by Django 2.2.5 on 2019-10-09 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bladework', '0004_auto_20191009_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='inspection_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
