# Generated by Django 2.2.5 on 2019-10-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bladework', '0005_damage_inspection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='width',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
